### ISSUE TITLE
Can't obtain xdai assets info

### ISSUE THREAD

**Issue by daviddavo** [Grasia/dao-analyzer#65]
I don't know if this is a temporal problem, but It can't get the token balance for xdai

```terminal
$ python -m cache_scripts -c daostack/tokenBalances
--- Updating daostack datawarehouse ---
Using block 0x199e4e7dd90200cfb50ee328f18aa017cf76a83fdb2b1ef3df5c678454b50748 for xdai (ts: 2022-03-25T12:34:15+00:00)
Running collector daostack/tokenBalances (xdai)
Requesting token balances:  14%|█████████████▋                                                                                  | 5/35 [00:02<00:15,  1.88req/s]ERROR: Requests failed with status code 500: Internal Server Error
Traceback (most recent call last):
  File "/home/davo/Documents/GRASIA/dao-analyzer/cache_scripts/common/common.py", line 233, in run
    c.run(force or olderBlock, blocks[c.network])
  File "/home/davo/Documents/GRASIA/dao-analyzer/cache_scripts/common/blockscout.py", line 106, in run
    df = pd.concat(map(toApply, ptqdm(addresses)), ignore_index=True)
  File "/home/davo/Documents/GRASIA/dao-analyzer/venv/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/davo/Documents/GRASIA/dao-analyzer/venv/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 346, in concat
    op = _Concatenator(
  File "/home/davo/Documents/GRASIA/dao-analyzer/venv/lib/python3.10/site-packages/pandas/core/reshape/concat.py", line 400, in __init__
    objs = list(objs)
  File "/home/davo/Documents/GRASIA/dao-analyzer/cache_scripts/common/blockscout.py", line 93, in _get_from_address
    raise ValueError(f"Requests failed with status code {r.status_code}: {r.reason}")
ValueError: Requests failed with status code 500: Internal Server Error

Requesting token balances:  14%|█████████████▋                                                                                  | 5/35 [00:02<00:17,  1.67req/s]
Using block 0xd98d02c07b54ca6e5af66eddbad660840cb8eef9e8a1d788a74dfc58317fb0f8 for mainnet (ts: 2022-03-25T12:02:14+00:00)
Running collector daostack/tokenBalances (mainnet)
Requesting token balances: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:05<00:00,  3.91req/s]
--- daostack's datawarehouse updated ---
```

**Comment by daviddavo** [comment]
It seems it was a temporal problem.

Nevertheless, I think this would be solved checking the transactions instead
